- name: Join Windows VM to Domain
  hosts: veeam-server
  vars_files:
    - "../vars/common.yml"
  tasks:
    - name: Ensure the computer is joined to the domain
      ansible.windows.win_domain_membership:
        domain_name: "{{ veeam.domain_name }}" 
        dns_domain_name: "{{ veeam.dns_domain_name }}"
        hostname: "{{ veeam.hostname }}" 
        domain_admin_user: "{{ veeam.domain_admin_user }}"
        domain_admin_password: "{{ veeam.domain_admin_password }}" 
        state: "domain"
      register: domain_join_result

    - name: Reboot the server if required
      ansible.windows.win_reboot:
      when: domain_join_result.reboot_required
